version: '3.8'

services:
  xhs-mcp:
    build: .
    container_name: xhs-mcp-server
    ports:
      - "8080:8080"  # MCP HTTP服务端口
      - "5901:5900"  # VNC端口
    environment:
      - VNC_MODE=true
      - HEADLESS_MODE=false
      - BROWSER_DATA_DIR=/app/browser_data
      - FASTMCP_HOST=0.0.0.0
      - FASTMCP_PORT=8080
      - FASTMCP_LOG_LEVEL=INFO
      - FASTMCP_MASK_ERROR_DETAILS=false
      
    volumes:
      - ./browser_data:/app/browser_data
      - ./logs:/app/logs
      - ./.env:/app/.env
      
    shm_size: 2gb
    restart: unless-stopped
    
    healthcheck:
      # 简化健康检查，只检查进程和端口，避免406错误
      test: ["CMD-SHELL", "pgrep -f 'python.*xiaohongshu_mcp_sse.py' && ss -tuln | grep -q ':8080 ' || exit 1"]
      interval: 60s  # 增加间隔，减少检查频率
      timeout: 10s
      retries: 3
      start_period: 120s  # 增加启动等待时间
    
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge