version: '3.8'

services:
  xhs-mcp:
    build: .
    container_name: xhs-mcp-server
    ports:
      - "8080:8080"  # MCP SSE端口
      - "5900:5900"  # VNC端口
    environment:
      # VNC模式配置
      - VNC_MODE=true
      
      # MCP服务器配置
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8080
      
      # 浏览器配置
      - HEADLESS_MODE=false
      - BROWSER_DATA_DIR=/app/browser_data
      
      # 可选：自动登录配置（headless模式用）
      # - XHS_USERNAME=your_username
      # - XHS_PASSWORD=your_password
      
    volumes:
      # 持久化浏览器数据
      - ./browser_data:/app/browser_data
      # 持久化日志
      - ./logs:/app/logs
      # 环境配置文件
      - ./.env:/app/.env
      
    restart: unless-stopped
    
    # 健康检查
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 60s
    
    # 资源限制（可选）
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: 2G
    #     reservations:
    #       cpus: '0.5'
    #       memory: 512M

# 网络配置（可选）
networks:
  default:
    name: xhs-mcp-network